#!/bin/bash
echo -e "\033[32mDeploying asset files to build\033[0m"
mkdir -p "build"
cp -R "assets" "build"
cp -R "data" "build"

cp *.tex "build"
cp *.sty "build"
cp *.bib "build"

mkdir -p "build/figures"
cp figures/*.tex "build/figures"

pushd "build" 1>/dev/null
rm -f "*.aux"


echo -e "\033[32mBuilding assets [Graphviz files to PDF]\033[0m"
find ./assets/ -name \*.dot -exec dot -O -Tpdf {} \; -exec prename -f 's/dot.pdf$/pdf/' {}.pdf \; -exec echo {} \;

echo -e "\033[32mBuilding assets [SVG to EPS with Inkscape]\033[0m"
find ./assets/ -name \*.svg -exec inkscape {} -E {}.eps \; -exec prename -f 's/svg.eps$/eps/' {}.eps \; -exec echo {} \;

echo -e "\033[32mBuilding assets [EPS to PDF with Ghostscript]\033[0m"
find ./assets/ -name \*.eps -exec epstopdf {} \; -exec echo {} \;

echo -e "\033[32mBuilding figures [xelatex]\033[0m"
find ./figures -name \*.tex -exec bash -c 'xelatex -halt-on-error "{}" 1>/dev/null || echo "Fail: {}"' \; -exec echo {} \;


popd 1>/dev/null

./make-doc
