#!/bin/bash
echo -e "\033[32mDeploying document files to build\033[0m"
mkdir -p "build"

cp *.tex "build"
cp *.cls "build"
cp *.sty "build"
cp ../thesis/*.bib "build"
cp ../thesis/terminology.tex "build"
ln -t build -s ../../thesis/data
cp -R backgrounds "build"
cp -R figures "build"

pushd "build" 1>/dev/null
rm -f "*.aux"

echo -e "\033[32mBuilding assets [SVG to EPS with Inkscape]\033[0m"
find ./figures/ -name \*.svg -exec inkscape {} -E {}.eps \; -exec prename -f 's/svg.eps$/eps/' {}.eps \; -exec echo {} \;

echo -e "\033[32mBuilding assets [EPS to PDF with Ghostscript]\033[0m"
find ./figures/ -name \*.eps -exec epstopdf {} \; -exec echo {} \;

echo -e "\033[32mBuilding latex [Pass 1/4: xelatex preprocess]\033[0m"
xelatex -halt-on-error -file-line-error "presentation.tex" 1>&2 || exit 1

echo -e "\033[32mBuilding latex [Pass 2/4: bibtex]\033[0m"
bibtex "presentation" 1>/dev/null || exit 1

echo -e "\033[32mBuilding latex [Pass 3/4: xelatex references]\033[0m"
xelatex -halt-on-error -file-line-error "presentation.tex" | grep -i ".*:[0-9]*:.*\|warning"

echo -e "\033[32mBuilding latex [Pass 4/4: xelatex with notes]\033[0m"
xelatex -halt-on-error -file-line-error "presentation.tex" | grep -i ".*:[0-9]*:.*\|warning"

sed -i 's/\\\\/\n/g' presentation.pdfpc
sed -i 's/\\par/\n\n/g' presentation.pdfpc

popd 1>/dev/null
